0 = [
        1,
        0
    ]
1 = [
        0,
        1
    ]

00 = [
        1,
        0,
        0,
        0
    ]
01 = [
        0,
        1,
        0,
        0
    ]
10 = [
        0,
        0,
        1,
        0
    ]
11 = [
        0,
        0,
        0,
        1
    ]

In [12]:
import numpy as np
import math

#0
q3 = np.array(
    [
        1,
        0
    ]
)
#0
q2 = np.array(
    [
        1,
        0
    ]
)
#1
q1 = np.array(
    [
        0,
        1
    ]
)




q2q1 = np.tensordot(q2,q1,axes=0).flatten()

print(q2q1)

q3q2q1 = np.tensordot(q3,q2q1,axes=0).flatten()

q3q2q1

[0 1 0 0]


array([0, 1, 0, 0, 0, 0, 0, 0])

In [13]:
import numpy as np

def basevector(amplitudes: np.ndarray) -> np.ndarray:
    if(amplitudes.size>=4):
        return np.tensordot(amplitudes[[0,1]],basevector(amplitudes[2:]),axes=0).flatten()
    else:
        return amplitudes

data = np.array(np.sqrt([(-2/4),(-2/4),-1,2,1,0.j,(2/4),(-2/4)]))

base_data = basevector(data)

print(base_data)



[-0.5       +0.j          0.        -0.5j         0.        +0.j
  0.        +0.j          0.        +0.70710678j -0.70710678+0.j
  0.        +0.j          0.        +0.j         -0.5       +0.j
  0.        -0.5j         0.        +0.j          0.        +0.j
  0.        +0.70710678j -0.70710678+0.j          0.        +0.j
  0.        +0.j        ]


[?,?,?,?,?,?,?,?] = sqrt([1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0] * 1/4)

[1,0,1,0,1,0,1,0] = [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

[1,0,0,1,1,0,0,1] = [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]

[0,1,1,0,1,0,1,0] = [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]

[0,1,0,1,1,0,0,1] = [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]

[(-2/4),(-2/4),i,sqrt(2),1,0,i,sqrt(2)]

In [14]:
from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector, DensityMatrix

data = np.array([1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0])
num_qubits = 4
circuit = QuantumCircuit(num_qubits)

data_normal = data/np.sqrt(np.sum(data**2))

circuit.initialize(data_normal)

state = Statevector(circuit)

display(state.draw("latex"))

<IPython.core.display.Latex object>

In [15]:
display(DensityMatrix(state).draw("latex"))

np.outer(data_normal, np.conj(data_normal))

<IPython.core.display.Latex object>

array([[0.25, 0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.25, 0.  , 0.  ,
        0.  , 0.  , 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.25, 0.  , 0.  ,
        0.  , 0.  , 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.25, 0.  , 0.  ,
        0.  , 0.  , 0.